import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';

const AppleSDGodicNeo = localFont({
  src: [
    {
      path: '../assets/fonts/AppleSDGothicNeo-Thin.woff2',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../assets/fonts/AppleSDGothicNeo-ExtraLight.woff2',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../assets/fonts/AppleSDGothicNeo-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../assets/fonts/AppleSDGothicNeo-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/AppleSDGothicNeo-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/fonts/AppleSDGothicNeo-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../assets/fonts/AppleSDGothicNeo-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/fonts/AppleSDGothicNeo-ExtraBold.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../assets/fonts/AppleSDGothicNeo-Black.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={AppleSDGodicNeo.className}>
      <body>{children}</body>
    </html>
  );
}
